### ISSUE TITLE
.completion-item .right {font-style: italic;} rule gets overrided

### ISSUE THREAD

**Issue by hagabaka** [1995eaton/chromium-vim#26]
In the cVim options I see a rule

``` css
.completion-item .right {
 font-style: italic;
 color: #888;
 width: 47%;
}
```

But the italic font-style does not get applied. In the inspector, I see a "user stylesheet" section that's overriding this:

``` css
.completion-item .right {
min-height: 0px;
border-radius: 0px;
box-sizing: content-box;
box-shadow: none;
margin: 0px;
-webkit-appearance: none;
letter-spacing: normal;
word-spacing: normal;
text-transform: none;
text-indent: 0px;
text-shadow: none;
text-align: start;
outline: none 0px;
border: 0px;
border-image-source: initial;
border-image-slice: initial;
border-image-width: initial;
border-image-outset: initial;
border-image-repeat: initial;
line-height: 1;
font-style: normal;
}
```

See screenshot:
![cvim-inspector](https://cloud.githubusercontent.com/assets/11416/2993178/428f261a-dca9-11e3-9498-aa07e4f3daf7.png)

Where is this coming from?
