### ISSUE TITLE
Increase Font Size at top?

### ISSUE THREAD

**Issue by quicknir** [1995eaton/chromium-vim#285]
I've found ways to increase the font size both of the HUD at the bottom right (shows you how many more search matches you have, what mode you're in) and the link hints, but I've not been able to increase the text size of the top bar. I find that it's quite small by default. Is there a setting for this that I missed in the configuration file?

**Comment by tatsumitagawa** [comment]
I was able to change the font size of the command bar by changing the first CSS statement. 

```css
#cVim-link-container, .cVim-link-hint, #cVim-command-bar, #cVim-command-bar-mode, #cVim-command-bar-input, #cVim-command-bar-search-results, .cVim-completion-item, .cVim-completion-item .cVim-full, .cVim-completion-item .cVim-left, .cVim-completion-item .cVim-right, #cVim-hud, #cVim-status-bar {
  font-family: Helvetica, Helvetica Neue, Neue, sans-serif, monospace, Arial;
  font-size: 10pt !important; /* CHANGE THIS FONT SIZE*/
  -webkit-font-smoothing: antialiased !important;
}
```
