### ISSUE TITLE
Help with CSS: Double height command bar.

### ISSUE THREAD

**Issue by achilleas-k** [1995eaton/chromium-vim#403]
I like having the command bar at the bottom, but as mentioned in #22, when the mouse pointer is hovering over a link, the URL at the bottom covers the bar.
I'm thinking that doubling the command bar's height would solve this issue, but I'm not sure how to make it happen using the user CSS configuration. I can get the bar to double height by changing the bar height to 40px from 20:
```css
#cVim-command-bar {
  height: 40px !important;
}
```

The problem with this is the command text is in the middle of the command bar (though the prompt `:` is at the top). How do I get the text to appear at the top of the command bar?

EDIT: Image attached
![screenshot_20160122_141351](https://cloud.githubusercontent.com/assets/2369197/12510420/6543592a-c112-11e5-9af4-500307648e47.png)

**Comment by fightingdreamer** [comment]
You only need:
```css
#cVim-command-bar {
  height: 45px !important;
}

#cVim-command-bar span, #cVim-command-bar input {
  height: auto !important;
  padding-top: 0.4em !important;
}

#cVim-command-bar-search-results {
  bottom: 45px !important;
}
```

![cvim](https://cloud.githubusercontent.com/assets/1376583/12889080/89822a0a-ce7d-11e5-8967-8155c1c03db3.png)
