### ISSUE TITLE
Suggestion: Bolder hints

### ISSUE THREAD

**Issue by itchyny** [1995eaton/chromium-vim#68]
First thing that I thought when I started to use cVim is that
the hints are not visible due to the thin font.
I prefer the hints bolder.

``` css
.cVim-link-hint {
  font-weight: bold !important;
}
```

Of course I know that I can configure.
But visibility matters for everyone who uses this extension.
What do you think?
